"use client";

import React, { useEffect, useState } from "react";
import { Finding, FindingStatus } from "@/types/finding";
import { getRemediationPlan } from "@/lib/remediation/plans";
import { CheckCircle2, Clipboard, Code2, ExternalLink, Lock, Play, X } from "lucide-react";

interface FindingDrawerProps { finding: Finding | null; status?: FindingStatus; onStatusChange?: (finding: Finding, status: FindingStatus) => void; onClose: () => void; onVerify?: () => void; }
const statusLabel: Record<FindingStatus, string> = { open: "OPEN", in_progress: "IN PROGRESS", marked_complete: "MARKED COMPLETE", verified_resolved: "VERIFIED RESOLVED" };

export const FindingDrawer: React.FC<FindingDrawerProps> = ({ finding, status = "open", onStatusChange, onClose, onVerify }) => {
  const [tab, setTab] = useState<"evidence" | "why" | "solution">("evidence");
  const [plainEnglish, setPlainEnglish] = useState(false);
  const [copied, setCopied] = useState(false);
  useEffect(() => { if (finding) { setTab("evidence"); setCopied(false); } }, [finding]);
  if (!finding) return null;
  const plan = getRemediationPlan(finding);
  const copyFix = async () => { if (plan.copyText) { await navigator.clipboard?.writeText(plan.copyText); setCopied(true); setTimeout(() => setCopied(false), 1800); } };
  const technical = `Detected ${finding.title.toLowerCase()}${finding.file ? ` in ${finding.file}` : ""}.`;
  const plain = finding.type === "secret" ? "This repository appears to contain a credential directly inside its code." : finding.type === "dependency" ? "This repository uses a package with a reported security issue." : "This repository has a configuration that may allow more access than intended.";
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/70 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={`Remediation for ${finding.title}`} onClick={onClose}>
    <aside className="w-full max-w-2xl h-full bg-radar-bg border-l border-radar-border shadow-2xl flex flex-col animate-in slide-in-from-right duration-300" onClick={(e) => e.stopPropagation()}>
      <header className="px-5 py-3 border-b border-radar-border bg-radar-surface/90 flex items-center justify-between gap-3"><div className="min-w-0"><p className="font-mono text-[10px] tracking-widest text-radar-textMuted">FINDING / REMEDIATION</p><h2 className="text-sm font-bold text-white truncate">{finding.title}</h2></div><button onClick={onClose} aria-label="Close remediation" className="p-2 text-radar-textMuted hover:text-white"><X className="w-5 h-5" /></button></header>
      <div className="flex-1 overflow-y-auto px-5 py-5 space-y-5">
        <div className="flex flex-wrap gap-2 items-center font-mono text-[10px]"><span className="px-2 py-1 border border-radar-critical/40 bg-radar-critical/10 text-radar-critical font-bold">{finding.severity.toUpperCase()}</span><span className="px-2 py-1 border border-radar-border text-radar-lime">{statusLabel[status]}</span>{finding.file && <span className="text-radar-textMuted flex items-center gap-1"><Code2 className="w-3 h-3" />{finding.file}{finding.line ? `:${finding.line}` : ""}</span>}</div>
        <div className="flex border-b border-radar-border" role="tablist" aria-label="Finding information">{(["evidence", "why", "solution"] as const).map((item) => <button key={item} role="tab" aria-selected={tab === item} onClick={() => setTab(item)} className={`px-3 py-2 text-[11px] font-mono ${tab === item ? "text-radar-lime border-b-2 border-radar-lime" : "text-radar-textMuted"}`}>{item === "why" ? "WHY IT MATTERS" : item.toUpperCase()}</button>)}</div>
        {tab === "evidence" && <section className="space-y-3"><p className="text-sm text-gray-300">{finding.description}</p>{finding.evidence?.redactedCode ? <><p className="font-mono text-[10px] text-radar-textMuted flex gap-1"><Lock className="w-3 h-3 text-radar-lime" />REDACTED EVIDENCE</p><pre className="p-3 bg-[#07070F] border border-radar-border text-xs font-mono text-gray-200 overflow-x-auto"><code>{finding.evidence.redactedCode}</code></pre></> : <p className="text-xs text-radar-textMuted">Evidence is represented by the package and advisory metadata shown below.</p>}{finding.package && <div className="p-3 border border-radar-border bg-radar-surface/60 text-xs font-mono grid grid-cols-2 gap-3"><span>PACKAGE <b className="block text-white">{finding.package.name}</b></span><span>INSTALLED <b className="block text-radar-high">{finding.package.version}</b></span>{finding.vulnerabilityId && <span>ADVISORY <b className="block text-white">{finding.vulnerabilityId}</b></span>}{finding.fixedVersion && <span>FIXED VERSION <b className="block text-radar-lime">{finding.fixedVersion}</b></span>}</div>}</section>}
        {tab === "why" && <section className="space-y-3"><div className="flex justify-end gap-1 font-mono text-[10px]"><button onClick={() => setPlainEnglish(false)} className={!plainEnglish ? "text-radar-lime" : "text-radar-textMuted"}>TECHNICAL</button><span>/</span><button onClick={() => setPlainEnglish(true)} className={plainEnglish ? "text-radar-lime" : "text-radar-textMuted"}>PLAIN ENGLISH</button></div><div className="p-4 border border-radar-border bg-radar-surface/60 text-sm leading-relaxed text-gray-300">{plainEnglish ? plain : technical}<p className="mt-3 text-xs text-radar-textMuted">{finding.whyItMatters}</p></div></section>}
        {tab === "solution" && <section className="space-y-4"><p className="text-sm leading-relaxed text-gray-300">{plan.summary}</p>{plan.steps.map((step, index) => <div key={step.title} className="flex gap-3"><span className="font-mono text-radar-lime text-xs">{String(index + 1).padStart(2, "0")}</span><div><h3 className="font-mono text-xs font-bold text-white">{step.title}</h3><p className="text-xs text-radar-textMuted leading-relaxed mt-1">{step.detail}</p>{step.providerUrl && <a className="inline-flex mt-2 text-[11px] font-mono text-radar-blue hover:text-radar-lime" target="_blank" rel="noopener noreferrer" href={step.providerUrl}>OPEN PROVIDER <ExternalLink className="w-3 h-3 ml-1" /></a>}</div></div>)}{plan.before && plan.after && <div className="grid sm:grid-cols-2 gap-3"><div><p className="font-mono text-[10px] text-radar-critical mb-1">BEFORE</p><pre className="overflow-x-auto p-3 bg-radar-critical/10 border border-radar-critical/30 text-xs text-red-200"><code>{plan.before}</code></pre></div><div><p className="font-mono text-[10px] text-radar-lime mb-1">AFTER</p><pre className="overflow-x-auto p-3 bg-radar-lime/10 border border-radar-lime/30 text-xs text-lime-100"><code>{plan.after}</code></pre></div></div>}{plan.copyText && <button onClick={copyFix} className="px-3 py-2 border border-radar-lime/50 text-radar-lime font-mono text-xs hover:bg-radar-lime hover:text-black"><Clipboard className="inline w-3 h-3 mr-1" />{copied ? "COPIED TO CLIPBOARD" : "COPY FIX"}</button>}</section>}
        {finding.references?.length ? <div className="flex flex-wrap gap-2">{finding.references.slice(0, 2).map((ref) => <a key={ref} href={ref} target="_blank" rel="noopener noreferrer" className="text-[10px] font-mono text-radar-blue">VIEW ADVISORY ↗</a>)}</div> : null}
      </div>
      <footer className="px-5 py-3 border-t border-radar-border bg-radar-surface/90 flex flex-wrap gap-2 justify-between"><button onClick={() => onStatusChange?.(finding, status === "marked_complete" ? "open" : "marked_complete")} className="px-3 py-2 text-xs font-mono border border-radar-border text-white hover:border-radar-lime"><CheckCircle2 className="inline w-3.5 h-3.5 mr-1 text-radar-lime" />{status === "marked_complete" ? "REOPEN" : "MARK COMPLETE"}</button><button onClick={onVerify} className="px-3 py-2 text-xs font-mono font-bold bg-radar-lime text-black"><Play className="inline w-3.5 h-3.5 mr-1" />RUN VERIFICATION SCAN</button></footer>
    </aside>
  </div>;
};
